# SPDX-FileCopyrightText: 2023-2025 KUNBUS GmbH
# SPDX-FileCopyrightText: 2026 Silitics GmbH
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Configuration file of cockpit-revpi

[WebService]
Origins = https://*.nexigon.dev https://*.nexigon.cloud https://*.nexigon.eu
ProtocolHeader = X-Forwarded-Proto
UrlRoot = /cockpit-revpi/
ForwardedForHeader = X-Forwarded-For
