[[persist]]
file = "/etc/revpi/factory-reset"

[[persist]]
file = "/etc/ssh/ssh_host_ecdsa_key"

[[persist]]
file = "/etc/ssh/ssh_host_ecdsa_key.pub"

[[persist]]
file = "/etc/ssh/ssh_host_ed25519_key"

[[persist]]
file = "/etc/ssh/ssh_host_ed25519_key.pub"

[[persist]]
file = "/etc/ssh/ssh_host_rsa_key"

[[persist]]
file = "/etc/ssh/ssh_host_rsa_key.pub"
